# chapter 1
## list and structure

### 1.1 ある文字列に重複する文字があるかどうか調べる

In [21]:
def check_str(s):
    s = list(s)
    c = s.copy()
    for i in c:
        s.pop(0)
        print(i, s)
        if i in s:
            return False
    return True

In [23]:
check_str("abcdefgh")


a ['b', 'c', 'd', 'e', 'f', 'g', 'h']
b ['c', 'd', 'e', 'f', 'g', 'h']
c ['d', 'e', 'f', 'g', 'h']
d ['e', 'f', 'g', 'h']
e ['f', 'g', 'h']
f ['g', 'h']
g ['h']
h []


True

### 1.2 文字列を反転

In [24]:
def reverse(s):
    return s[::-1]

In [25]:
reverse("abcdefgh")

'hgfedcba'

### 1.3 一方の文字列がもう一方の並び替えになっているかどうか

In [30]:
def sorting(s1, s2):
    s1, s2 = sorted(list(s1)), sorted(list(s2))
    for i, j in zip(s1, s2):
        if i != j:
            return False
    return True

In [32]:
sorting("abcdefgh", "cadbgf")

False

### 1.4 文字列の空白を"%20"で置き換えるメソッドを書け

In [33]:
def replace_str(s):
    return s.replace(' ', '%20')

In [34]:
replace_str("adfs  sefes ds")

'adfs%20%20sefes%20ds'

### 1.5 文字列の連続部を圧縮するメソッドを書け

In [1]:
def compress(s):
    s = list(s)
    c, cnt = "", 0
    l = []
    for i in s:
        if i != c:
            if cnt > 1:
                l.append(str(cnt))
            l.append(i)
            # init
            c = i
            cnt = 1
        else:
            cnt += 1
    if cnt > 1:
        l.append(str(cnt))
    
    return l
        

In [2]:
compress("aabcccccaaa")

['a', '2', 'b', 'c', '5', 'a', '3']

### 1.6 1pixel4bit四方の画像を90度回転させるプログラムを書け

In [3]:
import numpy as np
arr = np.random.randint(0, 2, (4, 8))
print(arr)

[[1 0 1 1 0 0 0 0]
 [0 0 1 0 0 0 1 0]
 [1 1 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0]]


In [7]:
arr.T[::-1]

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0]])

In [8]:
def roteto(arr):
    arr = arr.T[::-1]
    h, w = arr.shape
    for i in range(0, h, 2):
        for j in range(0, w, 2):
            arr[i][j], arr[i][j+1], arr[i+1][j+1], arr[i+1][j] = arr[i+1][j], arr[i][j], arr[i][j+1], arr[i+1][j+1]
    return arr

In [9]:
roteto(arr)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 1, 1],
       [0, 0, 0, 0]])